### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by d-solis-tovar** [adamlonsdale/pylivoltek#1]
Hi Adam,

I recently bought a Livoltek inverter and I'm trying to communicate with it via Livoltek API. The steps I'm following are:

1. Get token with securid and key
2. Include this token in headers: `headers = {"Authorization": token}`
3. Include previously-generated userToken in parameters: `params = {"userToken": userToken}`
4. Request the corresponding endpoint

After that, I got `{'code': '500', 'message': 'token.invalid'}`

However, when I make a request to `hess/api/powerStationStatistics` endpoint where no userToken is required, I get a valid response.

When generating userToken, effective date is set to "now time".

I'm quite stack on this and I can't find a solution. Hopefully you experienced some of these problems in the past.

Thank you in advance!

**Comment by adamlonsdale** [comment]
Hey @d-solis-tovar! Thanks for the info. 

Out of interest are you inside the EMEA area? I'm based in the UK so I have to use the EMEA endpoint to connect to the API. I'm writing an integration to Home Assistant for Livoltek and I have some example of using the API in the [helper.py](https://github.com/adamlonsdale/hass-livoltek/blob/main/custom_components/livoltek/helper.py) file within that project. 

In [async_get_api_client](https://github.com/adamlonsdale/hass-livoltek/blob/8404f17f5121d8165cae389ef7c9420acee2a46a/custom_components/livoltek/helper.py#L72) I set the relevant host and login. The [async_get_cur_power_flow](https://github.com/adamlonsdale/hass-livoltek/blob/8404f17f5121d8165cae389ef7c9420acee2a46a/custom_components/livoltek/helper.py#L109C11-L109C35) method then shows an example of using that to get the current power flow from the API. 

Let me know if you need anything else and I'd be happy to take a look!
